changes

diff --git a/.docker/scripts/init b/.docker/scripts/init
--- a/.docker/scripts/init
+++ b/.docker/scripts/init
@@ -1,21 +1,21 @@
 #!/bin/bash
 
-source ${LARADHOC_BASE_PATH}/.env
+source ${LARADHOC_BASE_PATH}/.laradhoc
 
 KEY_PATH="${LARADHOC_BASE_PATH}/.docker/images/nginx/ssl"
 
 if [ $NGINX_ENABLE_HTTPS == 1 ] && ! [ -x "$(command -v openssl)" ]; then
-  echo -e "\nError: openssl is not installed." >&2
-  echo -e "Please install openssl then try again.\n" >&2
-  exit 1
+    echo -e "\nError: openssl is not installed." >&2
+    echo -e "Please install openssl then try again.\n" >&2
+    exit 1
 fi
 
 if [ $NGINX_ENABLE_HTTPS == 1 ] ; then
-  echo "Creating a new self-signed certificate for domain '${APP_HOST}'..."
-  openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
+    echo "Creating a new self-signed certificate for domain '${APP_HOST}'..."
+    openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
     -subj "/C=CA/ST=QC/O=Company, Inc./CN=${APP_HOST}" \
     -out ${KEY_PATH}/${APP_HOST}.crt \
     -keyout ${KEY_PATH}/${APP_HOST}.key 2>/dev/null
 fi
 
-docker-compose --project-directory ${LARADHOC_BASE_PATH} --project-name "$CONTAINER_PREFIX" up --build $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+docker-compose --project-directory ${LARADHOC_BASE_PATH} --project-name "$CONTAINER_PREFIX" up -d --build $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
diff --git a/.docker/scripts/init-laravel b/.docker/scripts/init-laravel
--- a/.docker/scripts/init-laravel
+++ b/.docker/scripts/init-laravel
@@ -1,5 +1,5 @@
 #!/bin/bash
-source ${LARADHOC_BASE_PATH}/.env
+source ${LARADHOC_BASE_PATH}/.laradhoc
 
 _APP_SRC=${LARADHOC_BASE_PATH}/${APP_SRC}
 
@@ -9,20 +9,20 @@ TARGET_ENV="${_APP_SRC}/.env"
 TARGET_ENV_EXAMPLE="${_APP_SRC}/.env.example"
 
 if [ "$1" != "--new" ] ; then
-  # Existing project: check for .env file
-
-  if [ ! -f ${TARGET_ENV} ] ; then
-    # No .env file found. Try to copy it from .env.example
-    echo -e "\nNo ${TARGET_ENV} file found. Trying to copy from ${TARGET_ENV_EXAMPLE}..."
-    cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
+    # Existing project: check for .env file
 
     if [ ! -f ${TARGET_ENV} ] ; then
-      # Still no .env file
-      echo -e "\nERROR: there is no ${TARGET_ENV} file."
-      echo -e "Please create one manually, then run this script again.\n"
-      exit 1
+        # No .env file found. Try to copy it from .env.example
+        echo -e "\nNo ${TARGET_ENV} file found. Trying to copy from ${TARGET_ENV_EXAMPLE}..."
+        cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
+
+        if [ ! -f ${TARGET_ENV} ] ; then
+            # Still no .env file
+            echo -e "\nERROR: there is no ${TARGET_ENV} file."
+            echo -e "Please create one manually, then run this script again.\n"
+            exit 1
+        fi
     fi
-  fi
 fi
 
 
diff --git a/bin/laradhoc b/bin/laradhoc
--- a/bin/laradhoc
+++ b/bin/laradhoc
@@ -14,8 +14,8 @@ COMMAND=$1
 shift 1
 
 if [ "$COMMAND" == "" ] || [ "$COMMAND" == "help" ] ; then
-  ${LARADHOC_BASE_PATH}/.docker/scripts/help
-  exit 0
+    ${LARADHOC_BASE_PATH}/.docker/scripts/help
+    exit 0
 fi
 
 # Ensure that Docker is running
@@ -25,23 +25,19 @@ if ! docker info > /dev/null 2>&1; then
     exit 1
 fi
 
-# Ensure .env has been created
-if [ ! -f ${LARADHOC_BASE_PATH}/.env ]; then
-    echo -e "${ERROR}.env not found!${NC}\n" >&2
-    echo -e "Please, create a .env file before running commands.\n" >&2
-    echo -e "Run: cp .env.example .env\n" >&2
-    echo -e "Then edit your .env (see README.md)" >&2
-
+Ensure .env has been created
+if [ ! -f ${LARADHOC_BASE_PATH}/.laradhoc ]; then
+    echo -e "${ERROR}.laradhoc not found!${NC}\n" >&2
     exit 1
 fi
 
-source ${LARADHOC_BASE_PATH}/.env
+source ${LARADHOC_BASE_PATH}/.laradhoc
 
 # Ensure containers are running
 PSRESULT="$(docker-compose --project-directory ${LARADHOC_BASE_PATH} -p $CONTAINER_PREFIX ps -q)"
 if ! docker-compose --project-directory ${LARADHOC_BASE_PATH} -p $CONTAINER_PREFIX ps &> /dev/null; then
     EXEC="no"
-elif [ -n "$PSRESULT" ]; then
+    elif [ -n "$PSRESULT" ]; then
     EXEC="yes"
 else
     EXEC="no"
@@ -49,64 +45,63 @@ fi
 
 function check_if_is_running {
     if [ $EXEC == "no" ]; then
-      echo -e "${ERROR}Laradhoc is not running.${NC}" >&2
-      echo "" >&2
-      echo -e "You may start Laradhoc using the following command:${INFO} ./vendor/bin/laradhoc up${NC}\n" >&2
-
-      exit 1
+        echo -e "${ERROR}Laradhoc is not running.${NC}" >&2
+        echo "" >&2
+        echo -e "You may start Laradhoc using the following command:${INFO} ./vendor/bin/laradhoc up${NC}\n" >&2
+        exit 1
     fi
 }
 
 SCRIPTS_DIR=${LARADHOC_BASE_PATH}/.docker/scripts/
 
 if [ "$COMMAND" == "init" ]; then
-  ${SCRIPTS_DIR}init
-elif [ "$COMMAND" == "build" ]; then
-  ${SCRIPTS_DIR}start --build
-elif [ "$COMMAND" == "init-laravel" ]; then
-  ${SCRIPTS_DIR}init-laravel
-elif [ "$COMMAND" == "install-laravel" ]; then
-  ${SCRIPTS_DIR}install-laravel
-elif [ "$COMMAND" == "up" ] || [ "$COMMAND" == "start" ]; then
-  ${SCRIPTS_DIR}start
-elif [ "$COMMAND" == "down" ] || [ "$COMMAND" == "stop" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}stop
-elif [ "$COMMAND" == "artisan" ] || [ "$COMMAND" == "art" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}artisan $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
-elif [ "$COMMAND" == "tinker" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}artisan tinker
-elif [ "$COMMAND" == "composer" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}composer $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
-elif [ "$COMMAND" == "test" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}artisan test $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
-elif [ "$COMMAND" == "phpunit" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}phpunit $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
-elif [ "$COMMAND" == "ps" ]; then
-  check_if_is_running
-  docker-compose --project-directory ${LARADHOC_BASE_PATH} -p $CONTAINER_PREFIX ps
-elif [ "$COMMAND" == "nah" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}nah
-elif [ "$COMMAND" == "node" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}node $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
-elif [ "$COMMAND" == "gulp" ]; then
-  check_if_is_running
-  ${SCRIPTS_DIR}gulp $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
-elif [ "$COMMAND" == "php" ]; then
-  check_if_is_running
-  docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm $@
-elif [ "$COMMAND" == "fix" ]; then
-  check_if_is_running
-  docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm chown -R www:www vendor
-  docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm chown -R www:www storage
-  docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm php artisan storage:link
+    ${SCRIPTS_DIR}init
+    elif [ "$COMMAND" == "build" ]; then
+    ${SCRIPTS_DIR}start --build
+    elif [ "$COMMAND" == "init-laravel" ]; then
+    ${SCRIPTS_DIR}init-laravel
+    elif [ "$COMMAND" == "install-laravel" ]; then
+    ${SCRIPTS_DIR}install-laravel
+    elif [ "$COMMAND" == "up" ] || [ "$COMMAND" == "start" ]; then
+    ${SCRIPTS_DIR}start
+    elif [ "$COMMAND" == "down" ] || [ "$COMMAND" == "stop" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}stop
+    elif [ "$COMMAND" == "artisan" ] || [ "$COMMAND" == "art" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}artisan $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+    elif [ "$COMMAND" == "tinker" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}artisan tinker
+    elif [ "$COMMAND" == "composer" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}composer $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+    elif [ "$COMMAND" == "test" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}artisan test $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+    elif [ "$COMMAND" == "phpunit" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}phpunit $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+    elif [ "$COMMAND" == "ps" ]; then
+    check_if_is_running
+    docker-compose --project-directory ${LARADHOC_BASE_PATH} -p $CONTAINER_PREFIX ps
+    elif [ "$COMMAND" == "nah" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}nah
+    elif [ "$COMMAND" == "node" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}node $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+    elif [ "$COMMAND" == "gulp" ]; then
+    check_if_is_running
+    ${SCRIPTS_DIR}gulp $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
+    elif [ "$COMMAND" == "php" ]; then
+    check_if_is_running
+    docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm $@
+    elif [ "$COMMAND" == "fix" ]; then
+    check_if_is_running
+    docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm chown -R www:www vendor
+    docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm chown -R www:www storage
+    docker exec -u 0 -it ${CONTAINER_PREFIX}_php-fpm php artisan storage:link
 else
-  echo -e "\n${ERROR}Command '$COMMAND' not defined.${NC}\n"
+    echo -e "\n${ERROR}Command '$COMMAND' not defined.${NC}\n"
 fi
