refactor

diff --git a/.docker/scripts/init-laravel b/.docker/scripts/init-laravel
--- a/.docker/scripts/init-laravel
+++ b/.docker/scripts/init-laravel
@@ -1,26 +1,27 @@
 #!/bin/bash
-source ${LARADHOC_BASE_PATH}/.env
+source ${LARADHOC_BASE_PATH}/bin/.env
 
 _APP_SRC=${LARADHOC_BASE_PATH}/${APP_SRC}
 
 # Laravel .env file
-TARGET_ENV="${_APP_SRC}/.env.production"
+TARGET_ENV="${_APP_SRC}/.env"
 # Laravel .env.example file
 TARGET_ENV_EXAMPLE="${_APP_SRC}/.env.example"
 
-if [ ! -f ${TARGET_ENV} ] ; then
-    cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV}
-fi
-
 if [ "$1" != "--new" ] ; then
     # Existing project: check for .env file
-    cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
 
     if [ ! -f ${TARGET_ENV} ] ; then
-        # Still no .env file
-        echo -e "\nERROR: there is no ${TARGET_ENV} file."
-        echo -e "Please create one manually, then run this script again.\n"
-        exit 1
+        # No .env file found. Try to copy it from .env.example
+        echo -e "\nNo ${TARGET_ENV} file found. Trying to copy from ${TARGET_ENV_EXAMPLE}..."
+        cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
+
+        if [ ! -f ${TARGET_ENV} ] ; then
+            # Still no .env file
+            echo -e "\nERROR: there is no ${TARGET_ENV} file."
+            echo -e "Please create one manually, then run this script again.\n"
+            exit 1
+        fi
     fi
 fi
 
@@ -57,5 +58,3 @@ if [ "$1" != "--new" ] ; then
 fi
 
 ${LARADHOC_BASE_PATH}/.docker/scripts/artisan config:clear
-
-cp -f ${TARGET_ENV} ${LARADHOC_BASE_PATH}/.env
