fixed env prod

diff --git a/.docker/scripts/init-laravel b/.docker/scripts/init-laravel
--- a/.docker/scripts/init-laravel
+++ b/.docker/scripts/init-laravel
@@ -10,18 +10,13 @@ TARGET_ENV_EXAMPLE="${_APP_SRC}/.env.example"
 
 if [ "$1" != "--new" ] ; then
     # Existing project: check for .env file
+    cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
 
     if [ ! -f ${TARGET_ENV} ] ; then
-        # No .env file found. Try to copy it from .env.example
-        echo -e "\nNo ${TARGET_ENV} file found. Trying to copy from ${TARGET_ENV_EXAMPLE}..."
-        cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
-
-        if [ ! -f ${TARGET_ENV} ] ; then
-            # Still no .env file
-            echo -e "\nERROR: there is no ${TARGET_ENV} file."
-            echo -e "Please create one manually, then run this script again.\n"
-            exit 1
-        fi
+        # Still no .env file
+        echo -e "\nERROR: there is no ${TARGET_ENV} file."
+        echo -e "Please create one manually, then run this script again.\n"
+        exit 1
     fi
 fi
 
